//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace grabit_tests
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;


    public class WebTest1Coded : WebTest
    {

        public WebTest1Coded()
        {
            this.PreAuthenticate = true;
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("http://rad.msn.com/ADSAdClient31.dll");
            request1.Encoding = System.Text.Encoding.GetEncoding("iso-8859-1");
            request1.QueryStringParameters.Add("GetSAd", "", false, false);
            request1.QueryStringParameters.Add("DPJS", "4", false, false);
            request1.QueryStringParameters.Add("PN", "MSFT", false, false);
            request1.QueryStringParameters.Add("PG", "MSN9UT", false, false);
            request1.QueryStringParameters.Add("AP", "1402", false, false);
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("http://a.rad.msn.com/ADSAdClient31.dll");
            request2.Encoding = System.Text.Encoding.GetEncoding("iso-8859-1");
            request2.QueryStringParameters.Add("GetSAd", "", false, false);
            request2.QueryStringParameters.Add("DPJS", "4", false, false);
            request2.QueryStringParameters.Add("PN", "MSFT", false, false);
            request2.QueryStringParameters.Add("PG", "MSNVDC", false, false);
            request2.QueryStringParameters.Add("AP", "1071", false, false);
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("http://b.rad.msn.com/ADSAdClient31.dll");
            request3.Encoding = System.Text.Encoding.GetEncoding("iso-8859-1");
            request3.QueryStringParameters.Add("GetSAd", "", false, false);
            request3.QueryStringParameters.Add("DPJS", "4", false, false);
            request3.QueryStringParameters.Add("PN", "MSFT", false, false);
            request3.QueryStringParameters.Add("PG", "MSNCNT", false, false);
            request3.QueryStringParameters.Add("AP", "1463", false, false);
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("http://rad.msn.com/ADSAdClient31.dll");
            request4.Encoding = System.Text.Encoding.GetEncoding("iso-8859-1");
            request4.QueryStringParameters.Add("GetSAd", "", false, false);
            request4.QueryStringParameters.Add("DPJS", "4", false, false);
            request4.QueryStringParameters.Add("PN", "MSFT", false, false);
            request4.QueryStringParameters.Add("PG", "MSNREC", false, false);
            request4.QueryStringParameters.Add("AP", "1089", false, false);
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("http://a.rad.msn.com/ADSAdClient31.dll");
            request5.Encoding = System.Text.Encoding.GetEncoding("iso-8859-1");
            request5.QueryStringParameters.Add("GetSAd", "", false, false);
            request5.QueryStringParameters.Add("DPJS", "4", false, false);
            request5.QueryStringParameters.Add("PN", "MSFT", false, false);
            request5.QueryStringParameters.Add("PG", "MSNMML", false, false);
            request5.QueryStringParameters.Add("AP", "1402", false, false);
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest("http://b.rad.msn.com/ADSAdClient31.dll");
            request6.Encoding = System.Text.Encoding.GetEncoding("iso-8859-1");
            request6.QueryStringParameters.Add("GetSAd", "", false, false);
            request6.QueryStringParameters.Add("DPJS", "4", false, false);
            request6.QueryStringParameters.Add("PN", "MSFT", false, false);
            request6.QueryStringParameters.Add("PG", "MSNMMT", false, false);
            request6.QueryStringParameters.Add("AP", "1402", false, false);
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest("http://rad.msn.com/ADSAdClient31.dll");
            request7.Encoding = System.Text.Encoding.GetEncoding("iso-8859-1");
            request7.QueryStringParameters.Add("GetSAd", "", false, false);
            request7.QueryStringParameters.Add("DPJS", "4", false, false);
            request7.QueryStringParameters.Add("PN", "MSFT", false, false);
            request7.QueryStringParameters.Add("PG", "MSNSF1", false, false);
            request7.QueryStringParameters.Add("AP", "1402", false, false);
            yield return request7;
            request7 = null;

            WebTestRequest request8 = new WebTestRequest("http://a.rad.msn.com/ADSAdClient31.dll");
            request8.Encoding = System.Text.Encoding.GetEncoding("iso-8859-1");
            request8.QueryStringParameters.Add("GetSAd", "", false, false);
            request8.QueryStringParameters.Add("DPJS", "4", false, false);
            request8.QueryStringParameters.Add("PN", "MSFT", false, false);
            request8.QueryStringParameters.Add("PG", "MSNSH1", false, false);
            request8.QueryStringParameters.Add("AP", "1402", false, false);
            yield return request8;
            request8 = null;

            WebTestRequest request9 = new WebTestRequest("http://b.rad.msn.com/ADSAdClient31.dll");
            request9.Encoding = System.Text.Encoding.GetEncoding("iso-8859-1");
            request9.QueryStringParameters.Add("GetSAd", "", false, false);
            request9.QueryStringParameters.Add("DPJS", "4", false, false);
            request9.QueryStringParameters.Add("PN", "MSFT", false, false);
            request9.QueryStringParameters.Add("PG", "MSNSH2", false, false);
            request9.QueryStringParameters.Add("AP", "1402", false, false);
            yield return request9;
            request9 = null;

            WebTestRequest request10 = new WebTestRequest("http://rad.msn.com/ADSAdClient31.dll");
            request10.Encoding = System.Text.Encoding.GetEncoding("iso-8859-1");
            request10.QueryStringParameters.Add("GetSAd", "", false, false);
            request10.QueryStringParameters.Add("DPJS", "4", false, false);
            request10.QueryStringParameters.Add("PN", "MSFT", false, false);
            request10.QueryStringParameters.Add("PG", "MSNSH3", false, false);
            request10.QueryStringParameters.Add("AP", "1402", false, false);
            yield return request10;
            request10 = null;

            WebTestRequest request11 = new WebTestRequest("http://a.rad.msn.com/ADSAdClient31.dll");
            request11.Encoding = System.Text.Encoding.GetEncoding("iso-8859-1");
            request11.QueryStringParameters.Add("GetSAd", "", false, false);
            request11.QueryStringParameters.Add("DPJS", "4", false, false);
            request11.QueryStringParameters.Add("PN", "MSFT", false, false);
            request11.QueryStringParameters.Add("PG", "MSNSH4", false, false);
            request11.QueryStringParameters.Add("AP", "1402", false, false);
            yield return request11;
            request11 = null;

            WebTestRequest request12 = new WebTestRequest("http://b.rad.msn.com/ADSAdClient31.dll");
            request12.Encoding = System.Text.Encoding.GetEncoding("iso-8859-1");
            request12.QueryStringParameters.Add("GetSAd", "", false, false);
            request12.QueryStringParameters.Add("DPJS", "4", false, false);
            request12.QueryStringParameters.Add("PN", "MSFT", false, false);
            request12.QueryStringParameters.Add("PG", "MSNSUR", false, false);
            request12.QueryStringParameters.Add("AP", "1402", false, false);
            yield return request12;
            request12 = null;

            WebTestRequest request13 = new WebTestRequest("http://analytics.live.com/Sync.html");
            request13.QueryStringParameters.Add("V", "3525", false, false);
            request13.QueryStringParameters.Add("AQNT", "1", false, false);
            yield return request13;
            request13 = null;

            WebTestRequest request14 = new WebTestRequest("http://analytics.msn.com/Include.html");
            request14.ThinkTime = 7;
            yield return request14;
            request14 = null;

            WebTestRequest request15 = new WebTestRequest("http://74.8.243.133/");
            yield return request15;
            request15 = null;

            WebTestRequest request16 = new WebTestRequest("http://74.8.243.133/ALIS/WW400R.HTM");
            request16.QueryStringParameters.Add("WSIQTP", "SY40F", false, false);
            yield return request16;
            request16 = null;

            WebTestRequest request17 = new WebTestRequest("http://74.8.243.133/ALIS/WW400R.HTM");
            request17.QueryStringParameters.Add("WSIQTP", "SY40R", false, false);
            yield return request17;
            request17 = null;

            WebTestRequest request18 = new WebTestRequest("http://74.8.243.133/html/FITCHBRG/NoticeA.htm");
            yield return request18;
            request18 = null;

            WebTestRequest request19 = new WebTestRequest("http://74.8.243.133/favicon.ico");
            request19.ThinkTime = 1;
            request19.Encoding = System.Text.Encoding.GetEncoding("iso-8859-1");
            yield return request19;
            request19 = null;

            WebTestRequest request20 = new WebTestRequest("http://74.8.243.133/ALIS/WW400R.HTM");
            request20.ThinkTime = 2;
            request20.Encoding = System.Text.Encoding.GetEncoding("iso-8859-1");
            request20.QueryStringParameters.Add("WSIQTP", "SY40L", false, false);
            yield return request20;
            request20 = null;

            WebTestRequest request21 = new WebTestRequest("http://74.8.243.133/ALIS/WW400R.HTM");
            request21.ThinkTime = 4;
            request21.Encoding = System.Text.Encoding.GetEncoding("iso-8859-1");
            request21.QueryStringParameters.Add("WSIQTP", "LR09D", false, false);
            request21.QueryStringParameters.Add("WSKYCD", "E", false, false);
            ExtractHiddenFields extractionRule1 = new ExtractHiddenFields();
            extractionRule1.Required = true;
            extractionRule1.HtmlDecode = true;
            extractionRule1.ContextParameterName = "1";
            request21.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule1.Extract);
            yield return request21;
            request21 = null;

            WebTestRequest request22 = new WebTestRequest("http://74.8.243.133/ALIS/WW400R.HTM");
            request22.Method = "POST";
            request22.Encoding = System.Text.Encoding.GetEncoding("iso-8859-1");
            FormPostHttpBody request22Body = new FormPostHttpBody();
            request22Body.FormPostParameters.Add("W9FDTA", "01142010");
            request22Body.FormPostParameters.Add("W9TDTA", "01142010");
            request22Body.FormPostParameters.Add("W9ABR", "*ALL");
            request22Body.FormPostParameters.Add("W9TOWN", "*ALL");
            request22Body.FormPostParameters.Add("W9FC$", "");
            request22Body.FormPostParameters.Add("W9TC$", "");
            request22Body.FormPostParameters.Add("WSHTNM", this.Context["$HIDDEN1.WSHTNM"].ToString());
            request22Body.FormPostParameters.Add("WSIQTP", this.Context["$HIDDEN1.WSIQTP"].ToString());
            request22Body.FormPostParameters.Add("WSKYCD", this.Context["$HIDDEN1.WSKYCD"].ToString());
            request22.Body = request22Body;
            yield return request22;
            request22 = null;
        }
    }
}
